baseURL = "https://doongchoong.github.io"
languageCode = "ko-kr"
title = "둥충코딩"
theme = "hugo-theme-lhw" 
publishDir = "../"
staticDir="static"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
